name: Dependency Review

on:
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  dependency-review:
    uses: voyagi/.github-workflows/.github/workflows/dependency-review.yml@main
