name: Mirror to Codeberg

on:
  push:
    branches: [main, master]

jobs:
  mirror:
    uses: voyagi/.github-workflows/.github/workflows/mirror-codeberg.yml@main
    secrets:
      CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
